# ServerCaster Config #
# Make sure that you NEVER use tabs. Always use spaces or bukkit will complain. #
# Do not use apostrophes (') in you messages. The line will break if you do so. #
Prefix: '&RED;{[Broadcast]:}'
Interval: 20
InSeconds: false
Debug: false
Messages:
    - 'Colors are very easy to add. &GREEN;{Here is some green text!}'
    - 'You can also have broadcasts continue on the next line. &NEWLINE;Notice how the prefix &RED;{[Broadcast]:} was reprinted.'
    - 'You can have players execute commands by clicking chat! &GREEN;&UNDERLINE;&COMMAND;{say I love commands!}{Click here} to activate a test command!'
    - 'You can even use embedded links! &AQUA;&UNDERLINE;&URL;{"http://www.google.com/"}{Click here} to go to a website!'
    - 'You can use &COMMAND;{reloadservercast}{/reloadservercast} to reload the config file &NEWLINE;and use &COMMAND;{cast}{/cast} to cast the next message directly!'

