
Prefix: ''
Interval: 20
Debug: false
Messages:
    - '&RED;{[Broadcast]:} &GREEN;{Every month we are holding an event.}&RED;{[Broadcast]:}&NEWLINE;&YELLOW;{this time it is going to be the enderdragon fight on sunday the second of March.}&NEWLINE;&RED;{[Broadcast]:} &YELLOW;{for dates and times} &UNDERLINE;&YELLOW;&URL;{"http://fieldsofzen.site.nfoservers.com/"}{Here}'
    - '&RED;{[Broadcast]:} &UNDERLINE;&YELLOW;&URL;{"http://fieldsofzen.site.nfoservers.com/"}{Click Here} &YELLOW;{to go to our forums for information about maintenance and events!}'