name: BroadCaster
author: [killje, Flexo013]
description: a simple autoBroadcaster
version: 1.5
main: broadcaster.Broadcaster 
commands:
   reloadbroadcast:
      description: reloads the broadcast file
      usage: /reloadbroadcast
      permission: broadcaster.reload
   cast:
      description: broadcaste the next messege or the message with the specified message number
      usage: /broadcast [message number]
      permission: broadcaster.now