name: BroadCaster
author: [killje, Flexo013]
description: A broadcaster that can send messages at specified interval
version: 1.9-SNAPSHOT
main: me.servercaster.broadcaster.BroadCaster
commands:
   cast:
      description: Broadcast the next message to all groups.
      usage: §cThe correct format is /cast
      permission: servercaster.cast