# +----------------------------------------------------------------------------+
# | ServerCaster Config                                                        |
# +----------------------------------------------------------------------------+
# |Created by: Killje and Flexo013                                             |
# +----------------------------------------------------------------------------+
# |Make sure that you NEVER use tabs. Always use spaces or bukkit will complain|
# +----------------------------------------------------------------------------+
Prefix: '&RED;{[Broadcast]:}'