name: ServerCaster
author: [killje, Flexo013]
description: A broadcaster that can send clickable links and commands in chat as well as other chat effects
version: 1.8-SNAPSHOT
main: me.servercaster.core.ServerCaster
commands:
   reloadservercaster:
      description: Reloads the ServerCaster config file.
      usage: §cThe correct format is /reloadservercaster
      permission: servercaster.reload
   cast:
      description: Broadcast the next message to all groups.
      usage: §cThe correct format is /cast
      permission: servercaster.cast