name: ${project.callname}
author: ${project.authors}
description: ${project.description}
version: ${project.version}
main: ${project.main}
commands:
   reloadservercaster:
      description: Reloads the ServerCaster config file.
      usage: §cThe correct format is /reloadservercaster
      permission: servercaster.reload