name: ${project.callname}
author: ${project.authors}
description: ${project.description}
version: ${project.version}
main: ${project.main}
depend: ${project.depend}
softdepend: ${project.softdepend}